# Generated by Django 5.2.1 on 2025-05-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroestacionamento',
            options={'ordering': ['-data_registro'], 'verbose_name': 'Registro de Estacionamento', 'verbose_name_plural': 'Registros de Estacionamento'},
        ),
        migrations.AddField(
            model_name='registroestacionamento',
            name='tempo_total_segundos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroestacionamento',
            name='status',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10),
        ),
    ]
