# Generated by Django 5.2.1 on 2025-06-02 04:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registros', '0002_alter_registroestacionamento_options_and_more'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacaDetectada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8)),
                ('data_hora', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processada', 'Processada'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.registroestacionamento')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculos.veiculo')),
            ],
            options={
                'verbose_name': 'Placa Detectada',
                'verbose_name_plural': 'Placas Detectadas',
                'ordering': ['-data_hora'],
            },
        ),
    ]
